version: '3.8'
services:
  t8tp1-front:
    container_name: t8tp1-front
    build:
      dockerfile: ./inf/build/Dockerfile
    entrypoint: node index.js
    environment:
      - ORIGIN=https://t8tp1-front.lehadnk.com

  t8tp1-front-relay:
    container_name: t8tp1-front-relay
    image: nginx:latest
    restart: always
    volumes:
      - ./inf/prod/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"